#!/usr/bin/env bash

# git init with a .gitignore from the template in ~/.git_template/info/exclude
function gi {
	git init

	# git init hack to always have a .gitignore file since I forget to edit .git/info/exclude
	cat ./.git/info/exclude >> ./.gitignore
}

# Load a new tmux session from template $2 called $1 via tmuxp
function tp {
	if [ $# -lt 2 ] || [ $# -gt 2 ]; then
		echo "Create a new tmux session as"
		echo "\$ tp sessionName tmuxpTemplate"
		return
	fi

	# Open a new session via tmuxp
	TMUXP_SESSION_NAME=$1 tmuxp load $2
	unset TMUXP_SESSION_NAME
}

# Handy Extract Program
function extract() {
    if [ -f "$1" ] ; then
        case $1 in
            "*.tar.bz2")   tar xvjf "$1"     ;;
            "*.tar.gz")    tar xvzf "$1"     ;;
            "*.bz2")       bunzip2 "$1"      ;;
            "*.rar")       unrar x "$1"      ;;
            "*.gz")        gunzip "$1"       ;;
            "*.tar")       tar xvf "$1"      ;;
            "*.tbz2")      tar xvjf "$1"     ;;
            "*.tgz")       tar xvzf "$1"     ;;
            "*.zip")       unzip "$1"        ;;
            "*.Z")         uncompress "$1"   ;;
            "*.7z")        7z x "$1"         ;;
            "*")           echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
        echo "'$1' is not a valid file!"
    fi
}
