cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: true

  # Disable Neovim syntax
  env:
    neovim: false

policies:
  # Disable a violation
  ProhibitSomethingEvil:
    enabled: false

  # Enable a violation
  ProhibitSomethingBad:
    enabled: true
