" Colorscheme
function! CustomHighlights() abort
  " This overrides the current background in the colorscheme to NONE
  " Is used to get transparency in vim
  highlight Normal ctermbg=NONE
endfunction

augroup customColorscheme
  autocmd!
  autocmd ColorScheme * call CustomHighlights()
augroup END

scriptencoding utf-8

" Enable builtin matchit feature.
" Hit '%' on 'if' to jump to 'else'.
runtime macros/matchit.vim

set laststatus=2
call statusline#init()
